In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
import re
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Task #4/Sentiment (1).csv')

In [3]:
data.head()

id               candidate  candidate_confidence relevant_yn  \
0   1  No candidate mentioned                   1.0         yes   
1   2            Scott Walker                   1.0         yes   
2   3  No candidate mentioned                   1.0         yes   
3   4  No candidate mentioned                   1.0         yes   
4   5            Donald Trump                   1.0         yes   

   relevant_yn_confidence sentiment  sentiment_confidence     subject_matter  \
0                     1.0   Neutral                0.6578  None of the above   
1                     1.0  Positive                0.6333  None of the above   
2                     1.0   Neutral                0.6629  None of the above   
3                     1.0  Positive                1.0000  None of the above   
4                     1.0  Positive                0.7045  None of the above   

   subject_matter_confidence candidate_gold  ... relevant_yn_gold  \
0                     1.0000            NaN  ...              NaN   
1                     1.0000            NaN  ...              NaN   
2                     0.6629            NaN  ...              NaN   
3                     0.7039            NaN  ...              NaN   
4                     1.0000            NaN  ...              NaN   

  retweet_count  sentiment_gold subject_matter_gold  \
0             5             NaN                 NaN   
1            26             NaN                 NaN   
2            27             NaN                 NaN   
3           138             NaN                 NaN   
4           156             NaN                 NaN   

                                                text tweet_coord  \
0  RT @NancyLeeGrahn: How did everyone feel about...         NaN   
1  RT @ScottWalker: Didn't catch the full #GOPdeb...         NaN   
2  RT @TJMShow: No mention of Tamir Rice and the ...         NaN   
3  RT @RobGeorge: That Carly Fiorina is trending ...         NaN   
4  RT @DanScavino: #GOPDebate w/ @realDonaldTrump...         NaN   

               tweet_created            tweet_id  tweet_location  \
0  2015-08-07 09:54:46 -0700  629697200650592256             NaN   
1  2015-08-07 09:54:46 -0700  629697199560069120             NaN   
2  2015-08-07 09:54:46 -0700  629697199312482304             NaN   
3  2015-08-07 09:54:45 -0700  629697197118861312           Texas   
4  2015-08-07 09:54:45 -0700  629697196967903232             NaN   

                user_timezone  
0                       Quito  
1                         NaN  
2                         NaN  
3  Central Time (US & Canada)  
4                     Arizona  

[5 rows x 21 columns]

In [4]:
tweets = data[['sentiment', 'text']]

In [5]:
tweets

sentiment                                               text
0       Neutral  RT @NancyLeeGrahn: How did everyone feel about...
1      Positive  RT @ScottWalker: Didn't catch the full #GOPdeb...
2       Neutral  RT @TJMShow: No mention of Tamir Rice and the ...
3      Positive  RT @RobGeorge: That Carly Fiorina is trending ...
4      Positive  RT @DanScavino: #GOPDebate w/ @realDonaldTrump...
...         ...                                                ...
13866  Negative  RT @cappy_yarbrough: Love to see men who will ...
13867  Positive  RT @georgehenryw: Who thought Huckabee exceede...
13868  Positive  RT @Lrihendry: #TedCruz As President, I will a...
13869  Negative  RT @JRehling: #GOPDebate Donald Trump says tha...
13870  Positive  RT @Lrihendry: #TedCruz headed into the Presid...

[13871 rows x 2 columns]

In [6]:
tweets = tweets[tweets['sentiment']!= 'Neutral']

In [7]:
tweets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10729 entries, 1 to 13870
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  10729 non-null  object
 1   text       10729 non-null  object
dtypes: object(2)
memory usage: 251.5+ KB


In [8]:
#Data Prepocessing

In [9]:
train,test = train_test_split(tweets,test_size=0.1)

In [10]:
for val in train['text']:
    print(val)

Streaming output truncated to the last 5000 lines.
@ericbolling ppl say @realDonaldTrump needs specifics. so, WHY did #GOPDebate panel give all THOSE type of questions to opponents?! RIGGED!
GmaDawny: RT RhondaWatkGwyn: #ImWithHuck #GOPDebate #th2016 #ccot #tcot #teaparty #pjnet http://t.co/Ba4O0Kwluu
Ok, @tyeblue makes me giggle 😂 #Guuuurrrl #GOPdebate https://t.co/4JKa5BUHXv
RT @RWSurferGirl: Why should @realDonaldTrump pledge support to the GOP when the establishment sold out to Obama? #GOPDebate  #GOPDebates 🇺🇸
RT @louvice: Donald Will Go Independent! RubioNever Shows up 4 Work! #GopDebates
RT @marymauldin: Dig into everyone's financials if you are doing that to #Trump ! 
#GOPDebates
RT @RWSurferGirl: The candidates don't have to attack @realDonaldTrump Fox is doing it for them by stoping him from speaking. 🇺🇸 #GOPDebate…
Every time the camera cuts to Trump, he's grimacing like he's trying to break wind but avoid the shart... #GOPdebates
RT @jillwklausen: So how much fun was that t

In [11]:
pattern = "(@\w+)|(RT\s@\w+:)|(http.*)|(#\w+)"

In [12]:
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [13]:
def cleaning(data):
    cleaned_tweets = []
    sentiment = []
    for index, row in data.iterrows():
            sentence = re.sub(pattern, '', row.text)
            words = [e.lower() for e in sentence.split()]
            words = [lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')]
            cleaned_tweets.append(' '.join(words))
            sentiment.append(row.sentiment)

    return cleaned_tweets, sentiment

In [14]:
train_tweets, train_sentiment = cleaning(train)

In [15]:
train_tweets

['president, always tell truth, said would do.',
 'hey america, , sum up...',
 '7 takeaway like',
 'liberating hit "clear all" twitter alerts. sorry guys, shit make mental.',
 'think cruz trump need band together expose set job, get rid bush rubio, 🇺🇸 …',
 'trump fresh gaussian blur hair',
 'candidate attack fox stoping speaking. 🇺🇸 …',
 "love 's video re-cap :",
 'trump missed golden opp say, "know else filed bankruptcy? 50 cent. fifty p.i.m.p. sorry, huckabee.…',
 "far tell, gop. bunch unhappy people can't even agree unhappy about…",
 'huckabee look like one muppets balcony. name even sound like one.',
 'trump got right, nobody would talk immigration, untill brought up.',
 '"i time politically correct, time aggressively awful" -donald trump',
 'grilling fact grandfather helped found ?',
 'would never know frontrunner watching debate. 🇺🇸',
 'assume guy boo gay soldier time opportunity arise.',
 'support 1 u like still america pls vet u know ur getting!',
 'fox news admit republican le

In [16]:
final_data = {'tweets': train_tweets, 'sentiment': train_sentiment}

In [17]:
processed_data = pd.DataFrame(final_data)

In [18]:
processed_data

tweets sentiment
0          president, always tell truth, said would do.  Positive
1                              hey america, , sum up...  Negative
2                                       7 takeaway like  Negative
3     liberating hit "clear all" twitter alerts. sor...  Negative
4     think cruz trump need band together expose set...  Positive
...                                                 ...       ...
9651                        old tiresome b debate: blow  Negative
9652   jeb bush reminds elevator music. hear listen. 🇺🇸  Negative
9653  mean, matter question unfair? bother answering...  Negative
9654         fox news debate comedy laugh store... fun.  Negative
9655            thanks fox news, raising 's ratings. 🇺🇸  Positive

[9656 rows x 2 columns]

In [19]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
processed_data['sentiment'] = labelencoder.fit_transform(processed_data['sentiment'])

In [20]:
processed_data

tweets  sentiment
0          president, always tell truth, said would do.          1
1                              hey america, , sum up...          0
2                                       7 takeaway like          0
3     liberating hit "clear all" twitter alerts. sor...          0
4     think cruz trump need band together expose set...          1
...                                                 ...        ...
9651                        old tiresome b debate: blow          0
9652   jeb bush reminds elevator music. hear listen. 🇺🇸          0
9653  mean, matter question unfair? bother answering...          0
9654         fox news debate comedy laugh store... fun.          0
9655            thanks fox news, raising 's ratings. 🇺🇸          1

[9656 rows x 2 columns]

In [21]:
from collections import Counter
value_counts = Counter(processed_data['sentiment'])

# Iterate through the results to print each value and its count
for value, count in value_counts.items():
    print(f"'{value}': {count} times")


'1': 1992 times
'0': 7664 times


In [22]:
# Converting words into Vectors

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))
cv.fit(processed_data['tweets'])

CountVectorizer(ngram_range=(1, 3))

In [24]:
X_train = cv.transform(processed_data['tweets'])

In [25]:
print(X_train.shape)

(9656, 82092)


In [26]:
target = processed_data['sentiment'].values

In [27]:
target

array([1, 0, 0, ..., 0, 0, 1])

In [28]:
#Cleaning Test Data and Converting Test data into vactors

In [29]:
#Cleaning for Test
test_tweets, test_sentiment = cleaning(test)

In [30]:
Test_data = {'tweets': test_tweets, 'sentiment': test_sentiment}

In [31]:
processed_test_data = pd.DataFrame(Test_data)

In [32]:
processed_test_data

tweets sentiment
0                             term substance, dominates  Positive
1     hey ! absolutely fearful ? i'm lol refuse ask ...  Negative
2     people watch 's see realize "holy crap effing ...  Positive
3                    haha little saas morning towards .  Negative
4             listening recap day work..... fun........  Positive
...                                                 ...       ...
1068  three question i'd ask : 1. nice waiters? 2. g...  Negative
1069  rand paul gone with, 'i've got curly hair!' dr...  Negative
1070  oh boy: "social issues" = gop code control wom...  Negative
1071  look like last night highest rated primary deb...  Positive
1072      anyone else want punch chris wallace face? 🇺🇸  Negative

[1073 rows x 2 columns]

In [53]:
X_test = cv.transform(processed_test_data['tweets'])

In [54]:
print(X_test.shape)

(1073, 82092)


In [55]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [56]:
#Sentiment Analysis model

In [57]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

In [58]:
classifier.fit(X_train.toarray(),target)

MultinomialNB()

In [59]:
y_predict = classifier.predict(X_test.toarray())

In [60]:
y_predict

array([1, 0, 0, ..., 0, 1, 0])

In [61]:
#in order to check accuracy we have to encode Test Data Sentiment first
processed_test_data['sentiment'] = labelencoder.fit_transform(processed_test_data['sentiment'])

In [45]:
processed_test_data

tweets  sentiment
0                             term substance, dominates          1
1     hey ! absolutely fearful ? i'm lol refuse ask ...          0
2     people watch 's see realize "holy crap effing ...          1
3                    haha little saas morning towards .          0
4             listening recap day work..... fun........          1
...                                                 ...        ...
1068  three question i'd ask : 1. nice waiters? 2. g...          0
1069  rand paul gone with, 'i've got curly hair!' dr...          0
1070  oh boy: "social issues" = gop code control wom...          0
1071  look like last night highest rated primary deb...          1
1072      anyone else want punch chris wallace face? 🇺🇸          0

[1073 rows x 2 columns]

In [46]:
actual_values = processed_test_data['sentiment'].values

In [47]:
actual_values

array([1, 0, 1, ..., 0, 1, 0])

In [62]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_predict,actual_values))

0.8452935694315005


In [64]:
processed_test_data


tweets  sentiment
0                             term substance, dominates          1
1     hey ! absolutely fearful ? i'm lol refuse ask ...          0
2     people watch 's see realize "holy crap effing ...          1
3                    haha little saas morning towards .          0
4             listening recap day work..... fun........          1
...                                                 ...        ...
1068  three question i'd ask : 1. nice waiters? 2. g...          0
1069  rand paul gone with, 'i've got curly hair!' dr...          0
1070  oh boy: "social issues" = gop code control wom...          0
1071  look like last night highest rated primary deb...          1
1072      anyone else want punch chris wallace face? 🇺🇸          0

[1073 rows x 2 columns]

In [65]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [66]:
classifier.predict(X_test.toarray()[[1071]])

array([1])